# Generated by Django 4.2.2 on 2024-07-29 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='действие')),
                ('when', models.CharField(max_length=255, verbose_name='время')),
                ('place', models.CharField(max_length=255, verbose_name='место')),
                ('is_nice', models.BooleanField(default=False, verbose_name='приятная')),
                ('reward', models.CharField(max_length=512, verbose_name='вознаграждение')),
                ('period', models.PositiveSmallIntegerField(default=1, verbose_name='периодичность (дней)')),
                ('duration', models.PositiveSmallIntegerField(default=2, verbose_name='продолжительность (минут)')),
                ('is_public', models.BooleanField(default=False, verbose_name='публичная')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habit.habit', verbose_name='связанная привычка')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
