# Generated by Django 4.2.2 on 2024-07-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0003_alter_habit_when'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='is_nice',
            new_name='is_pleasant',
        ),
        migrations.AlterField(
            model_name='habit',
            name='duration',
            field=models.PositiveSmallIntegerField(default=120, verbose_name='продолжительность (секунд)'),
        ),
    ]
