# Generated by Django 4.2.2 on 2024-07-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0004_rename_is_nice_habit_is_pleasant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='reward',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='вознаграждение'),
        ),
    ]
